cmake_minimum_required(VERSION 3.13)

foreach(required_var SOURCE_ROOT BUILD_ROOT SLIC3R_APP_KEY MULTI_CONFIG)
    if(NOT DEFINED ${required_var} OR "${${required_var}}" STREQUAL "")
        message(FATAL_ERROR "Missing required variable: ${required_var}")
    endif()
endforeach()
if(NOT SLIC3R_APP_KEY MATCHES "^[A-Za-z][A-Za-z0-9_-]*$")
    message(FATAL_ERROR "Invalid application directory name: ${SLIC3R_APP_KEY}")
endif()
if(MULTI_CONFIG AND (NOT DEFINED CONFIG OR NOT CONFIG MATCHES "^[A-Za-z0-9_-]+$"))
    message(FATAL_ERROR "Invalid build configuration: ${CONFIG}")
endif()

get_filename_component(SOURCE_ROOT "${SOURCE_ROOT}" ABSOLUTE)
get_filename_component(BUILD_ROOT "${BUILD_ROOT}" ABSOLUTE)
get_filename_component(build_parent "${BUILD_ROOT}" DIRECTORY)
if(BUILD_ROOT STREQUAL SOURCE_ROOT OR BUILD_ROOT STREQUAL build_parent)
    message(FATAL_ERROR "Refusing to reset data_dir in a source or filesystem root")
endif()
if(NOT EXISTS "${BUILD_ROOT}/CMakeCache.txt")
    message(FATAL_ERROR "Not a configured build directory: ${BUILD_ROOT}")
endif()
file(STRINGS "${BUILD_ROOT}/CMakeCache.txt" cached_source
    REGEX "^CMAKE_HOME_DIRECTORY:INTERNAL=")
string(REGEX REPLACE "^CMAKE_HOME_DIRECTORY:INTERNAL=" "" cached_source "${cached_source}")
get_filename_component(cached_source "${cached_source}" REALPATH)
get_filename_component(expected_source "${SOURCE_ROOT}" REALPATH)
if(NOT cached_source STREQUAL expected_source)
    message(FATAL_ERROR "Build directory belongs to a different source tree: ${BUILD_ROOT}")
endif()

function(inlong_check_data_dir_path path)
    if(IS_SYMLINK "${path}")
        message(FATAL_ERROR "Refusing to reset linked build data_dir path: ${path}")
    endif()
    if(EXISTS "${path}")
        get_filename_component(resolved "${path}" REALPATH)
        set(expected "${path}")
        if(WIN32)
            string(TOLOWER "${resolved}" resolved)
            string(TOLOWER "${expected}" expected)
        endif()
        if(NOT resolved STREQUAL expected)
            message(FATAL_ERROR "Refusing to reset redirected build data_dir path: ${path}")
        endif()
    endif()
endfunction()

inlong_check_data_dir_path("${BUILD_ROOT}")
if(MULTI_CONFIG)
    set(binary_dir "${BUILD_ROOT}/src/${CONFIG}")
else()
    set(binary_dir "${BUILD_ROOT}/src")
endif()
set(data_dirs
    "${binary_dir}/data_dir"
    "${BUILD_ROOT}/${SLIC3R_APP_KEY}/data_dir"
    "${BUILD_ROOT}/${SLIC3R_APP_KEY}_InlongOnly/data_dir"
)

# Preflight every target before removing anything. This includes parent directory
# junctions and nested links, which must never redirect a recursive removal.
foreach(data_dir IN LISTS data_dirs)
    set(parent "${data_dir}")
    while(NOT parent STREQUAL BUILD_ROOT)
        inlong_check_data_dir_path("${parent}")
        get_filename_component(parent "${parent}" DIRECTORY)
    endwhile()
    if(IS_DIRECTORY "${data_dir}")
        file(GLOB_RECURSE contents LIST_DIRECTORIES TRUE "${data_dir}/*")
        foreach(content IN LISTS contents)
            inlong_check_data_dir_path("${content}")
        endforeach()
    endif()
endforeach()

foreach(data_dir IN LISTS data_dirs)
    file(REMOVE_RECURSE "${data_dir}")
    file(MAKE_DIRECTORY "${data_dir}")
    file(GLOB contents "${data_dir}/*")
    if(NOT IS_DIRECTORY "${data_dir}" OR contents)
        message(FATAL_ERROR "Could not create an empty build data_dir: ${data_dir}")
    endif()
    message(STATUS "Empty portable data_dir: ${data_dir}")
endforeach()
